### ISSUE TITLE
Move the version number into the package

### ISSUE THREAD

**Issue by peterbe** [mozilla/socorrolib#7]
Because the version number is [hardcoded in setup.py](https://github.com/mozilla/socorrolib/blob/03642ce1edd96bc383ea11e9c7a467b9f6ec771f/setup.py#L37) you can't do things like
```python
>>> import socorrolib
>>> socorrolib.__version__
```

**Comment by peterbe** [comment]
I suggest we put it into `socorrolib/__init__.py` and parse that out from within the `setup.py`. 
cc @willkg @lonnen

**Comment by willkg** [comment]
I've seen this listed as a good practice for exactly this reason. It's easy to change if we want to do it. I'm happy to fix it.

**Comment by peterbe** [comment]
> I'm happy to fix it.

Please do. 

Another alternative is to mess with setuptools. E.g. something like this (untested):
```python
>>> import pkg_resources
>>> pkg_resources.get_distribution("socorrolib").version
```

**Comment by peterbe** [comment]
E.g. http://stackoverflow.com/questions/710609/checking-a-python-module-version-at-runtime/4939465#4939465

Note, that's still possible. But if we do it in a variable called `__version__` you can do both.

**Comment by lonnen** [comment]
fixed by PR #12

**Comment by peterbe** [comment]
This breaks testing. 

```
$ nosetests
E
======================================================================
ERROR: Failure: DistributionNotFound (The 'socorrolib' distribution was not found and is required by the application)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/peterbe/virtualenvs/socorrolib/lib/python2.7/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/peterbe/virtualenvs/socorrolib/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/peterbe/virtualenvs/socorrolib/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/peterbe/dev/MOZILLA/SOCORRO/socorrolib/socorrolib/__init__.py", line 3, in <module>
    __version__ = get_distribution('socorrolib').version
  File "/Users/peterbe/virtualenvs/socorrolib/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in get_distribution
    dist = get_provider(dist)
  File "/Users/peterbe/virtualenvs/socorrolib/lib/python2.7/site-packages/pkg_resources/__init__.py", line 422, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/Users/peterbe/virtualenvs/socorrolib/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/peterbe/virtualenvs/socorrolib/lib/python2.7/site-packages/pkg_resources/__init__.py", line 830, in resolve
    raise DistributionNotFound(req, requirers)
DistributionNotFound: The 'socorrolib' distribution was not found and is required by the application

----------------------------------------------------------------------
Ran 1 test in 0.013s

FAILED (errors=1)
```

Which makes sense. I haven't installed it yet. I guess we can just tell people to run `python setup.py install` first.

**Comment by lonnen** [comment]
re-fixed in kind of a hacky way: https://github.com/mozilla/socorrolib/commit/70ed0a36aa994630b852b3bb98525bd4bfb2d1bd
